version: '3.5'

services:
    hdfs:
        container_name: "hdfs"
        build:
            context: .
            dockerfile: infrastructures/hdfs/Dockerfile
        ports:
            - "9500:9500"
        environment:
            - PORT=9500
            - NAME=HDFS
            - DEBUG=1
        restart: always
        env_file:
            - .env
        volumes:
            - ./src/services/hdfs/:/src/app/
            - shared-workspace:/opt/workspace
        networks:
            - spark-net

    spark-master:
        image: ${SPARK_VERSION}
        ports:
            - "7077:7077"
            - "8090:8080"
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            -  shared-workspace:/opt/workspace
        networks:
            - spark-net

    spark-worker:
        image: ${SPARK_VERSION}
        environment:
            - SPARK_MODE=worker
            - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
            - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
            - SPARK_DRIVER_MEMORY=${SPARK_DRIVER_MEMORY}
            - SPARK_EXECUTOR_MEMORY=${SPARK_EXECUTOR_MEMORY}
            - SPARK_MASTER=spark://master:7077
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        deploy:
            replicas: ${REPLICAS:-0}
        volumes:
            -  shared-workspace:/opt/workspace
        networks:
            - spark-net
        depends_on:
            - spark-master

volumes:
    shared-workspace:
        external: true
        name: pres3-spark_shared-workspace

networks:
    spark-net:
        external: true




